name: Reusable Deploy Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      DATABASE_URL_DEV:
        required: true
      DATABASE_URL_PROD:
        required: true
      AWS_ECR_REGISTRY_URL:
        required: true

env:
  AWS_REGION: ap-southeast-1
  ECR_REPO_APP: lbta-app-app
  ECR_REPO_API: lbta-app-api
  APP_SERVICE: app-service
  API_SERVICE: api-service

jobs:
  deploy:
    name: Deploy to AWS ECS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set Environment Variables
        run: |
          # Set common variables
          echo "DATABASE_NAME=lbtaapp" >> $GITHUB_ENV
          if [ "${{ inputs.environment }}" == "dev" ]; then
            echo "ENV=dev" >> $GITHUB_ENV
            echo "ECS_CLUSTER=dev-lbta-app-cluster" >> $GITHUB_ENV
            echo "ORIGIN_URL=https://tasks.saltandsun.life" >> $GITHUB_ENV
            echo "DATABASE_URL=${{ secrets.DATABASE_URL_DEV }}" >> $GITHUB_ENV
            echo "AWS_ECR_REGISTRY_APP=${{ secrets.AWS_ECR_REGISTRY_URL }}/dev-${{ env.ECR_REPO_APP }}" >> $GITHUB_ENV
            echo "AWS_ECR_REGISTRY_API=${{ secrets.AWS_ECR_REGISTRY_URL }}/dev-${{ env.ECR_REPO_API }}" >> $GITHUB_ENV
            echo "NEXT_PUBLIC_API_URL=https://api.saltandsun.life" >> $GITHUB_ENV
            echo "NEXT_PUBLIC_APP_URL=https://tasks.saltandsun.life" >> $GITHUB_ENV
            echo "API_URL=https://api.saltandsun.life" >> $GITHUB_ENV
            echo "APP_URL=https://tasks.saltandsun.life" >> $GITHUB_ENV
          else
            echo "ENV=prod" >> $GITHUB_ENV
            echo "ECS_CLUSTER=prod-lbta-app-cluster" >> $GITHUB_ENV
            echo "ORIGIN_URL=https://tasks.saltandsun.life" >> $GITHUB_ENV
            echo "DATABASE_URL=${{ secrets.DATABASE_URL_PROD }}" >> $GITHUB_ENV
            echo "AWS_ECR_REGISTRY_APP=${{ secrets.AWS_ECR_REGISTRY_URL }}/prod-${{ env.ECR_REPO_APP }}" >> $GITHUB_ENV
            echo "AWS_ECR_REGISTRY_API=${{ secrets.AWS_ECR_REGISTRY_URL }}/prod-${{ env.ECR_REPO_API }}" >> $GITHUB_ENV
            echo "NEXT_PUBLIC_API_URL=https://api.saltandsun.ph" >> $GITHUB_ENV
            echo "NEXT_PUBLIC_APP_URL=https://tasks.saltandsun.life" >> $GITHUB_ENV
            echo "API_URL=https://api.saltandsun.ph" >> $GITHUB_ENV
            echo "APP_URL=https://tasks.saltandsun.life" >> $GITHUB_ENV
          fi

      - name: Debug ECR Registry URL
        run: |
          echo "AWS_ECR_REGISTRY_URL: ${{ secrets.AWS_ECR_REGISTRY_URL }}"
          echo "AWS_ECR_REGISTRY_APP: $AWS_ECR_REGISTRY_APP"

      - name: Build and Push Frontend Image
        env:
          NEXT_PUBLIC_API_URL: ${{ env.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_APP_URL: ${{ env.NEXT_PUBLIC_APP_URL }}
          API_URL: ${{ env.API_URL }}
          APP_URL: ${{ env.APP_URL }}
        run: |
          echo "Building image with tag: $AWS_ECR_REGISTRY_APP:latest"
          docker build -t $AWS_ECR_REGISTRY_APP:latest -f app/Dockerfile app
          docker push $AWS_ECR_REGISTRY_APP:latest

      - name: Build and Push Backend Image
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
          DATABASE_NAME: ${{ env.DATABASE_NAME }}
          ORIGIN_URL: ${{ env.ORIGIN_URL }}
        run: |
          docker build -t $AWS_ECR_REGISTRY_API -f api/Dockerfile api
          docker push $AWS_ECR_REGISTRY_API

      - name: Deploy Frontend to ECS
        run: |
          aws ecs update-service --cluster $ECS_CLUSTER --service $APP_SERVICE --force-new-deployment

      - name: Deploy Backend to ECS
        run: |
          aws ecs update-service --cluster $ECS_CLUSTER --service $API_SERVICE --force-new-deployment
